services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'userdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'