spring:
  application:
    name: User-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
server:
  error:
    include-binding-errors: ALWAYS
    include-message: ALWAYS
  servlet:
    context-path: /user